version: '3.1'
services:
  db:
    image: postgres:14
    user: root
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  odoo:
    image: odoo:12.0
    user: root
    depends_on:
      - db
    ports:
      - "0.0.0.0:8068:8068"
    volumes:
      - ./addons:/mnt/c/__WORK__/taskflow
